# Generated by Django 3.0.3 on 2020-04-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloTestMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_title', models.CharField(max_length=10)),
                ('hello_body', models.TextField()),
                ('publishing_date', models.DateTimeField()),
            ],
        ),
    ]
