# Generated by Django 3.0.7 on 2020-07-17 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hw_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hellotestmessage',
            name='publishing_date',
        ),
        migrations.AddField(
            model_name='hellotestmessage',
            name='publishing_dt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 17, 20, 54, 5, 662157, tzinfo=utc)),
        ),
    ]
