# Generated by Django 3.0.7 on 2020-07-21 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hw_test', '0002_auto_20200717_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellotestmessage',
            name='publishing_dt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 13, 23, 17, 838185, tzinfo=utc)),
        ),
    ]
