# Generated by Django 3.0.7 on 2020-07-21 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hw_test', '0003_auto_20200721_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellotestmessage',
            name='publishing_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
