# Generated by Django 3.0.7 on 2020-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_test', '0004_auto_20200721_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='hellotestmessage',
            name='hello_title',
            field=models.CharField(max_length=20),
        ),
    ]
