# Generated by Django 3.0.7 on 2020-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_test', '0006_imagefilemodel_message_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImageMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('image_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='imagefilemodel',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='imagefilemodel',
            name='message_name',
        ),
    ]
