# Generated by Django 3.0.7 on 2020-11-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_test', '0007_auto_20201028_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefilemodel',
            name='image_file',
            field=models.ImageField(upload_to='image_upload_folder/'),
        ),
    ]
